### ISSUE TITLE
DeadObjectException: Transaction failed on small parcel; remote process probably died

### ISSUE THREAD

**Issue by kenumir** [kenumir/ApkInfo#1]
Stack trace:
```
!!! FAILED BINDER TRANSACTION !!!  (parcel size = 132)
java.lang.RuntimeException: Package manager has died
    at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:220)
    at com.wt.apkinfo.db.DatabaseCreator$1.doInBackground(DatabaseCreator.java:98)
    at com.wt.apkinfo.db.DatabaseCreator$1.doInBackground(DatabaseCreator.java:86)
    at android.os.AsyncTask$2.call(AsyncTask.java:295)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    at java.lang.Thread.run(Thread.java:818)
Caused by: android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
    at android.os.BinderProxy.transactNative(Native Method)
    at android.os.BinderProxy.transact(Binder.java:503)
    at android.content.pm.IPackageManager$Stub$Proxy.getPackageInfo(IPackageManager.java:2730)
    at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:215)
```

**Comment by kenumir** [comment]
Fixed

**Comment by trinhvanvinh** [comment]
how to fix

**Comment by kenumir** [comment]
Limit package manager query to activities or services only, more queries, less data in result.
